### PR TITLE
Fix filtering when rule contains `Like` operator

### LINKED ISSUE #205: Instance Filter Dialog: filter is not working with `Like` operator

### PR DESCRIPTION
**Pull request by simasjar**
closes #205

### CODE REVIEW

File: packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts [hunk 1]
```diff
@@ -224,7 +224,11 @@ function handleStringifiedValues(filter: PresentationInstanceFilterCondition, se
   let selectedValueIndex = 0;
 
   const { displayValues, groupedRawValues } = deserializeDisplayValueGroupArray(serializedDisplayValues, serializedGroupedRawValues);
-  if (displayValues === undefined || groupedRawValues === undefined) {
+  if (
+    displayValues === undefined ||
+    groupedRawValues === undefined ||
+    (operator !== PropertyFilterRuleOperator.IsEqual && operator !== PropertyFilterRuleOperator.IsNotEqual)
```
Comment (saskliutas) [inline packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts:230]: I think operator should be checked in `convertUniqueValuesCondition` function before trying to deserialize values.

**Review by saskliutas — CHANGES_REQUESTED** [review]

File: packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts (hunk 1 above)
Comment (simasjar) [reply packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts]: fixed

Comment (simasjar) [reply packages/components/src/presentation-components/instance-filter-builder/InstanceFilterConverter.ts]: fixed

**Review by saskliutas — APPROVED** [review]
